In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/glass.csv')
df

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [ ]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [ ]:
df.tail()

RI     Na   Mg    Al     Si     K    Ca    Ba   Fe  Type
209  1.51623  14.14  0.0  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.0  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.0  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.0  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.0  2.08  73.36  0.00  8.62  1.67  0.0     7

In [ ]:
df.shape

(214, 10)

In [ ]:
df.dtypes

RI      float64
Na      float64
Mg      float64
Al      float64
Si      float64
K       float64
Ca      float64
Ba      float64
Fe      float64
Type      int64
dtype: object

In [ ]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [ ]:
df.describe()

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516522   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1.000000  
25%      8.240000    0.000000    0.000000    1.000000  
50%      8.600000    0.000000    0.000000    2.000000  
75%      9.172500    0.000000    0.100000    3.000000  
max     16.190000    3.150000    0.510000    7.000000

In [ ]:
df1=df['Type'].value_counts()
df1

2    76
1    70
7    29
3    17
5    13
6     9
Name: Type, dtype: int64

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
x

array([[ 1.52101, 13.64   ,  4.49   , ...,  8.75   ,  0.     ,  0.     ],
       [ 1.51761, 13.89   ,  3.6    , ...,  7.83   ,  0.     ,  0.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  7.78   ,  0.     ,  0.     ],
       ...,
       [ 1.52065, 14.36   ,  0.     , ...,  8.44   ,  1.64   ,  0.     ],
       [ 1.51651, 14.38   ,  0.     , ...,  8.48   ,  1.57   ,  0.     ],
       [ 1.51711, 14.23   ,  0.     , ...,  8.62   ,  1.67   ,  0.     ]])

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [ ]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)


In [ ]:
x_train

array([[ 1.5159 , 12.82   ,  3.52   , ...,  7.97   ,  0.     ,  0.     ],
       [ 1.51934, 13.64   ,  3.54   , ...,  8.89   ,  0.15   ,  0.24   ],
       [ 1.51818, 13.72   ,  0.     , ..., 10.99   ,  0.     ,  0.     ],
       ...,
       [ 1.51588, 13.12   ,  3.41   , ...,  8.39   ,  0.     ,  0.19   ],
       [ 1.51852, 14.09   ,  2.19   , ...,  9.32   ,  0.     ,  0.     ],
       [ 1.5182 , 12.62   ,  2.76   , ...,  9.42   ,  0.     ,  0.2    ]])

In [ ]:
x_test

array([[1.51755e+00, 1.30000e+01, 3.60000e+00, 1.36000e+00, 7.29900e+01,
        5.70000e-01, 8.40000e+00, 0.00000e+00, 1.10000e-01],
       [1.51727e+00, 1.47000e+01, 0.00000e+00, 2.34000e+00, 7.32800e+01,
        0.00000e+00, 8.95000e+00, 6.60000e-01, 0.00000e+00],
       [1.52152e+00, 1.30500e+01, 3.65000e+00, 8.70000e-01, 7.22200e+01,
        1.90000e-01, 9.85000e+00, 0.00000e+00, 1.70000e-01],
       [1.51602e+00, 1.48500e+01, 0.00000e+00, 2.38000e+00, 7.32800e+01,
        0.00000e+00, 8.76000e+00, 6.40000e-01, 9.00000e-02],
       [1.51708e+00, 1.37200e+01, 3.68000e+00, 1.81000e+00, 7.20600e+01,
        6.40000e-01, 7.88000e+00, 0.00000e+00, 0.00000e+00],
       [1.52739e+00, 1.10200e+01, 0.00000e+00, 7.50000e-01, 7.30800e+01,
        0.00000e+00, 1.49600e+01, 0.00000e+00, 0.00000e+00],
       [1.51761e+00, 1.28100e+01, 3.54000e+00, 1.23000e+00, 7.32400e+01,
        5.80000e-01, 8.39000e+00, 0.00000e+00, 0.00000e+00],
       [1.51569e+00, 1.32400e+01, 3.49000e+00, 1.47000e+00, 7.

In [ ]:
y_train

array([2, 3, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 7, 2, 5, 1, 1, 2, 1, 7, 5,
       2, 1, 2, 6, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 5, 2, 1, 3, 2, 2, 1, 2,
       2, 2, 1, 2, 1, 3, 2, 2, 2, 2, 1, 7, 1, 1, 2, 2, 1, 1, 7, 6, 1, 1,
       2, 7, 3, 1, 1, 2, 3, 2, 3, 2, 1, 1, 2, 3, 6, 1, 7, 3, 2, 5, 1, 1,
       2, 1, 2, 1, 7, 3, 2, 1, 7, 1, 2, 5, 1, 3, 1, 2, 1, 2, 7, 5, 7, 1,
       2, 1, 1, 2, 2, 2, 7, 7, 2, 1, 1, 1, 6, 2, 1, 5, 2, 7, 2, 6, 7, 1,
       1, 2, 1, 5, 7, 5, 1, 1, 2, 1, 1, 3, 7, 7, 2, 1, 3, 7, 1, 1, 3, 2,
       3, 2, 2, 2, 2, 7, 2, 2, 7, 1, 7, 2, 2, 1, 2, 6, 2])

In [ ]:
y_test

array([1, 7, 1, 7, 2, 2, 1, 2, 2, 2, 6, 5, 2, 2, 6, 5, 7, 1, 1, 6, 2, 7,
       7, 7, 3, 2, 1, 1, 5, 1, 1, 2, 3, 2, 1, 7, 5, 3, 2, 2, 2, 7, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)


In [ ]:
x_train

array([[-0.84623746, -0.74467528,  0.52636164, ..., -0.68807645,
        -0.33761134, -0.60110996],
       [ 0.28077633,  0.33413832,  0.54088841, ..., -0.03692037,
        -0.04564469,  1.78472688],
       [-0.0992632 ,  0.43938842, -2.03034913, ...,  1.44941417,
        -0.33761134, -0.60110996],
       ...,
       [-0.85278986, -0.34998738,  0.44646443, ..., -0.39080954,
        -0.33761134,  1.28767753],
       [ 0.0121277 ,  0.92617017, -0.43966828, ...,  0.26742432,
        -0.33761134, -0.60110996],
       [-0.09271079, -1.00780055, -0.02565546, ...,  0.33820216,
        -0.33761134,  1.3870874 ]])

In [ ]:
x_test

array([[-3.05663981e-01, -5.07862542e-01,  5.84468704e-01,
        -1.21495330e-01,  5.15619125e-01,  1.24478619e-01,
        -3.83731760e-01, -3.37611336e-01,  4.92398588e-01],
       [-3.97397661e-01,  1.72870223e+00, -2.03034913e+00,
         1.93716871e+00,  8.94259024e-01, -8.95952920e-01,
         5.54633328e-03,  9.47041914e-01, -6.01109964e-01],
       [ 9.94988561e-01, -4.42081225e-01,  6.20785619e-01,
        -1.15082735e+00, -4.89735091e-01, -5.55809074e-01,
         6.42546850e-01, -3.37611336e-01,  1.08885780e+00],
       [-8.06923021e-01,  1.92604619e+00, -2.03034913e+00,
         2.02119582e+00,  8.94259024e-01, -8.95952920e-01,
        -1.28931554e-01,  9.08113028e-01,  2.93578851e-01],
       [-4.59645516e-01,  4.39388422e-01,  6.42575767e-01,
         8.23809587e-01, -6.98639863e-01,  2.49794773e-01,
        -7.51776503e-01, -3.37611336e-01, -6.01109964e-01],
       [ 2.91811965e+00, -3.11280269e+00, -2.03034913e+00,
        -1.40290866e+00,  6.33128059e-01, -8.959529

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

array([1, 7, 1, 7, 2, 2, 1, 2, 2, 1, 6, 2, 1, 2, 6, 5, 7, 1, 1, 7, 2, 7,
       7, 7, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 7, 5, 1, 1, 2, 1, 7, 2])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
result

array([[10,  1,  0,  0,  0,  0],
       [ 5,  9,  0,  0,  0,  0],
       [ 1,  2,  0,  0,  0,  0],
       [ 0,  2,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  2,  1],
       [ 0,  0,  0,  0,  0,  8]])

In [ ]:
score=accuracy_score(y_test,y_pred)
score

0.7209302325581395

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.62      0.91      0.74        11
           2       0.64      0.64      0.64        14
           3       0.00      0.00      0.00         3
           5       1.00      0.50      0.67         4
           6       1.00      0.67      0.80         3
           7       0.89      1.00      0.94         8

    accuracy                           0.72        43
   macro avg       0.69      0.62      0.63        43
weighted avg       0.70      0.72      0.69        43



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
